### ISSUE TITLE
16 device limit?

### ISSUE THREAD

**Issue by bklavet** [makermusings/fauxmo#10]
Thanks for putting this on GitHub and the blogs about it.  Do you know if the 16 device limit is still the max amount of WeMo the echo can detect or has that been expanded?

**Comment by ramgarden** [comment]
Could this be easily tested by adding 17 or more fake devices to the FAUXMOS array then telling Alexa to discover devices and see what she says?  I could do this tonight and test it if it's that easy.

**Comment by thexperiments** [comment]
the problem still is there... any chance to work around this?
