### ISSUE TITLE
"That command doesn't work on that device"

### ISSUE THREAD

**Issue by Funcan** [makermusings/fauxmo#13]
So, just experimenting.

I run up out-of-the-box fauxmo on my workstation, do a scan on the Echo, it correctly finds 2 devices. Great!

The debug output looks right:

```
duncan@z640:~/src/fauxmo$ python ./fauxmo.py -d
Listening for UPnP broadcasts
got local address of 10.0.0.9
UPnP broadcast listener: new device registered
FauxMo device 'office lights' ready on 10.0.0.9:49726
UPnP broadcast listener: new device registered
FauxMo device 'kitchen lights' ready on 10.0.0.9:49131
Entering main loop

Responding to search for office lights
Responding to search for kitchen lights
Responding to search for office lights
Responding to search for kitchen lights
Responding to setup.xml for kitchen lights
Responding to setup.xml for office lights
Responding to setup.xml for office lights
Responding to setup.xml for kitchen lights
Responding to search for office lights
Responding to search for kitchen lights
Responding to search for office lights
Responding to search for kitchen lights
Responding to setup.xml for office lights
Responding to setup.xml for kitchen lights
Responding to setup.xml for office lights
Responding to setup.xml for kitchen lights
```

I then say 'Alexa, turn on the office lights'. The debug looks good:

```
Responding to ON for office lights
```

But a short time after, Alexa responds with 'That command is not support by that device'. It then gives the same answer for kitchen lights, without and output from fauxmo. Some time later, the debug output printed is:

```
('Connection aborted.', error(110, 'Connection timed out'))
```

Any help greatfully appreciated. I'll try to do some debug of my own in the meantime.

**Comment by ramgarden** [comment]
Looks like the fauxmo tried to issue that command but the actual device timed out on that request.  
First thing, did you update the FAUXMOS array to point to the URL for your actual devices' on and off "commands" or did you leave that default?  If so then those IP addresses won't be there on your network so it will time out every time.
Otherwise to debug, you could "manually" browse to the URLs set in the on and off "commands" in your FAUXMOS array.  If you put that same URL for the on "command" for the office lights does it work or also time out in the browser?

**Comment by Funcan** [comment]
You're right, I didn't read enough of the docs, I haven't actually configured my devices in fauxmo yet, Thanks!

**Comment by waccolon** [comment]
# **Alexa Error That Command Doesn't Work**

My name is Willie Colón (Cologne) www.williecolon.com @williecolon facebook.com/thewilliecolon I have solved the Alexa device problem!  Please get back to me if it works for you WACCO1@LIVE.COM. Get a piece of paper to write this down...  Make sure your echo is connected and working. Tell Alexa "Discover devices" DONE! 

**## Do it through Alexa not the app!**
