### ISSUE TITLE
run script instead of URI ?

### ISSUE THREAD

**Issue by matphillips** [makermusings/fauxmo#19]
Is there an easy way to modify the code so that instead of making an API call to a URL, it can instead execute a bash script? Calling a method in the main fauxmo.py file could be ok too.

I have very little experience with python, so I don't instantly see how to accomplish this, but if there's a quick way it would be better for me than the alternative of setting up a web server on the Raspberry Pi and writing a handler to receive the call and then execute the script/code; seems nicer to do it directly.

What I am trying to achieve is to integrate this with a 433MHz library to send pulses over GPIO to a transmitter installed on the Pi, so Alexa can control regular (cheap) 433 power sockets.

**Comment by OldNo7** [comment]
Check out my fork of this project. I added a handler for controlling GPIO pins on a Pi. I was turning relays on and off but you could easily change the code in the ON/OFF section.

[OldNo7/fauxmo](https://github.com/OldNo7/fauxmo )

**Comment by matphillips** [comment]
thank you, that helped show me the correct way to do it (plus, my hack wasnt working!)
I've now added a "rf_handler(object)" class to send the codes, and added a 100ms sleep after sending because when multiples were activated at once, sometime they didn't all trigger.
Got it working perfectly now; voice control over five outlets without breaking the bank!
