### ISSUE TITLE
Any Android App available to control Fauxmo emulated switches ?

### ISSUE THREAD

**Issue by MopheusDG** [makermusings/fauxmo#20]
Hi, I know Wemo apps don't work with Fauxmo cause it's only emulating part of the Wemo, so my question is, is there any other app available that can control this switches with my phone too (apart from Alexa) ?

Thanks.

**Comment by pr3sidentspence** [comment]
Well, I have three things set up. I can use Apple Home and any Homekit app, but it requires:

Fauxmo. Home Assistant which sees the Fauxmo switches. And Homebridge, which imports Home Assistant's devices and exposes them to Homekit.

This also allows Homekit apps to control real Wemo switches, which will never happen otherwise.

**Comment by pr3sidentspence** [comment]
Oh, I'm using the forked version of fauxmo, FYI: https://github.com/n8henrie/fauxmo/issues.

Oh, and I *just* noticed that you said Android in you subject. Sorry.

**Comment by MopheusDG** [comment]
Yeah, I was thinking of something simplier, like just be able to send a http request or similar to my Fauxmo (running on an ESP8266) and turn on the lights or whatever, so that not only I can control it using Alexa but also Wifi with my cellphone or tablet. The problem is that Wemo apps do not work as they use a more complicate setting that Alexa requieres, at least from what I read around.

**Comment by MopheusDG** [comment]
I can write my own Java app for Android (have some basic skills) but don't know what format and protocol should I send to the ESP to be able to, for example, send a Light One On to the Wemo emulator.

**Comment by ScriptSorcererUK** [comment]
I use this app to run commands via ssh on the raspberry pi fauxmo is running on. But I'd love one that discovers all the fauxmo devices automatically and lists them in a nice format with on/off buttons.

https://play.google.com/store/apps/details?id=org.openobjectives.serverassistant

**Comment by Houba28** [comment]
need something too... I want to try my esp8266 fauxmo running device befor buying alexa... best would be an android app, but can be tested with python or C# script on my computer, if it works... found pywemo, but it seems not working, cannot detect device, also with IP adress...

**Comment by mrdvt92** [comment]
You can use the Open Source Perl project Power::Outlet. It has an [Apache CGI script](https://metacpan.org/source/MRDVT/Power-Outlet-0.20/scripts/power-outlet.cgi) that comes with the project and has an HTML-based button UI.

Look at the RPM spec file for guidance, if you need to install it on a non-RPM-based OS.
