### ISSUE TITLE
How to delete emulated device from Alexa app?

### ISSUE THREAD

**Issue by bhattvishal** [makermusings/fauxmo#28]
I added few devices using Fauxmo that got discovered in Alexa, and then later renamed the devices, now Alexa shows all the devices old and new. My issue is how to delete old devices from Alexa.

**Comment by mcbaer** [comment]
The Alexa mobile app.

**Comment by bhattvishal** [comment]
@mB-PiBox  There is no option to delete device, the only options I see is to disable the device.

**Comment by mcbaer** [comment]
Then use http://alexa.amazon.com .. as fauxmo doesn't control what devices Alexa remember or forgets.

**Comment by bhattvishal** [comment]
@mB-PiBox Perfect!! Thanks, I can now forgot (delete) devices from Alexa.
