### ISSUE TITLE
16 switch limit

### ISSUE THREAD

**Issue by HariComputes** [makermusings/fauxmo#30]
Hi,

I wasn't sure where to post this question so correct me if this is the wrong place.

The 16 switch limit. Is that per pi or is that in total for alexa.

E.g. can i have 16 switch on one raspberry pi and then another 16 on another or is it a total of 16 switches in the household?

(Sorry for a repetition, i know similar issues are submitted occasionally, but i just needed a bit of clarification)

**Comment by makermusings** [comment]
The limit, as far as I know, is for your entire household, even if you have multiple Echo devices.

**Comment by HariComputes** [comment]
So, if i have a raspberry pi running 12 switches on it, and another raspberry pi running 8, it will only detect 16 of the switches?

**Comment by makermusings** [comment]
I believe that's correct. What's worse, the subset of 16 from your total of 20 switches may change unpredictably each time the Echo looks for devices.

**Comment by HariComputes** [comment]
Damn, that's kinda annoying. With how versatile the use case of fauxmo is, they restrict the usage for it. :/

I guess i'll have to look at other ways of doing things. Thanks for the information.

**Comment by mrdvt92** [comment]
I have moved to HomeAssistant https://home-assistant.io/  You might want to give it a try.  I know of no limits when using its component driver model.
